<template>
    <div class="song-continent">
        <div id="app" style="width: 100%; height: 100%;">
            <network :nodeList="nodes" :linkList="links"></network>
        </div>
    </div>
</template>

<script>
import Network from "vue-network-d3";

export default {
  name: "app",
  components: {
    Network
  },
  data() {
    return {
      nodes: [
	{"id": "关键词", "group": "林俊杰"},
	{"id": "期待爱", "group": "林俊杰"},
	{"id": "一千年以后", "group": "林俊杰"},
	{"id": "江南", "group": "林俊杰"},
	{"id": "学不会", "group": "林俊杰"},
	{"id": "醉赤壁", "group": "林俊杰"},
	{"id": "仰望星空", "group": "张杰"},
	{"id": "他不懂", "group": "张杰"},
	{"id": "天下", "group": "张杰"},
	{"id": "如果爱", "group": "张杰"},
	{"id": "逆战", "group": "张杰"},
	{"id": "逆态度", "group": "张杰"},
	{"id": "何必在一起", "group": "张杰"},
	{"id": "剑心", "group": "张杰"},
	{"id": "稻香", "group": "周杰伦"},
	{"id": "告白气球", "group": "周杰伦"},
	{"id": "夜曲", "group": "周杰伦"},
	{"id": "红尘客栈", "group": "周杰伦"},
	{"id": "开不了口", "group": "周杰伦"},
	{"id": "菊花台", "group": "周杰伦"},
	{"id": "牛仔很忙", "group": "周杰伦"},
	{"id": "烟花易冷", "group": "周杰伦"},
	{"id": "听妈妈的话", "group": "周杰伦"},
	{"id": "七里香", "group": "周杰伦"},
	{"id": "晴天", "group": "周杰伦"},
],
links: [
	{"source": "关键词", "target": "关键词"},
	{"source": "关键词", "target": "期待爱"},
	{"source": "关键词", "target": "一千年以后"},
	{"source": "关键词", "target": "江南"},
	{"source": "关键词", "target": "学不会"},
	{"source": "关键词", "target": "醉赤壁"},
	{"source": "期待爱", "target": "关键词"},
	{"source": "期待爱", "target": "期待爱"},
	{"source": "期待爱", "target": "一千年以后"},
	{"source": "期待爱", "target": "江南"},
	{"source": "期待爱", "target": "学不会"},
	{"source": "期待爱", "target": "醉赤壁"},
	{"source": "一千年以后", "target": "关键词"},
	{"source": "一千年以后", "target": "期待爱"},
	{"source": "一千年以后", "target": "一千年以后"},
	{"source": "一千年以后", "target": "江南"},
	{"source": "一千年以后", "target": "学不会"},
	{"source": "一千年以后", "target": "醉赤壁"},
	{"source": "江南", "target": "关键词"},
	{"source": "江南", "target": "期待爱"},
	{"source": "江南", "target": "一千年以后"},
	{"source": "江南", "target": "江南"},
	{"source": "江南", "target": "学不会"},
	{"source": "江南", "target": "醉赤壁"},
	{"source": "学不会", "target": "关键词"},
	{"source": "学不会", "target": "期待爱"},
	{"source": "学不会", "target": "一千年以后"},
	{"source": "学不会", "target": "江南"},
	{"source": "学不会", "target": "学不会"},
	{"source": "学不会", "target": "醉赤壁"},
	{"source": "醉赤壁", "target": "关键词"},
	{"source": "醉赤壁", "target": "期待爱"},
	{"source": "醉赤壁", "target": "一千年以后"},
	{"source": "醉赤壁", "target": "江南"},
	{"source": "醉赤壁", "target": "学不会"},
	{"source": "醉赤壁", "target": "醉赤壁"},
	{"source": "关键词", "target": "仰望星空"},
	{"source": "仰望星空", "target": "仰望星空"},
	{"source": "仰望星空", "target": "他不懂"},
	{"source": "仰望星空", "target": "天下"},
	{"source": "仰望星空", "target": "如果爱"},
	{"source": "仰望星空", "target": "逆战"},
	{"source": "仰望星空", "target": "逆态度"},
	{"source": "仰望星空", "target": "何必在一起"},
	{"source": "仰望星空", "target": "剑心"},
	{"source": "他不懂", "target": "仰望星空"},
	{"source": "他不懂", "target": "他不懂"},
	{"source": "他不懂", "target": "天下"},
	{"source": "他不懂", "target": "如果爱"},
	{"source": "他不懂", "target": "逆战"},
	{"source": "他不懂", "target": "逆态度"},
	{"source": "他不懂", "target": "何必在一起"},
	{"source": "他不懂", "target": "剑心"},
	{"source": "天下", "target": "仰望星空"},
	{"source": "天下", "target": "他不懂"},
	{"source": "天下", "target": "天下"},
	{"source": "天下", "target": "如果爱"},
	{"source": "天下", "target": "逆战"},
	{"source": "天下", "target": "逆态度"},
	{"source": "天下", "target": "何必在一起"},
	{"source": "天下", "target": "剑心"},
	{"source": "如果爱", "target": "仰望星空"},
	{"source": "如果爱", "target": "他不懂"},
	{"source": "如果爱", "target": "天下"},
	{"source": "如果爱", "target": "如果爱"},
	{"source": "如果爱", "target": "逆战"},
	{"source": "如果爱", "target": "逆态度"},
	{"source": "如果爱", "target": "何必在一起"},
	{"source": "如果爱", "target": "剑心"},
	{"source": "逆战", "target": "仰望星空"},
	{"source": "逆战", "target": "他不懂"},
	{"source": "逆战", "target": "天下"},
	{"source": "逆战", "target": "如果爱"},
	{"source": "逆战", "target": "逆战"},
	{"source": "逆战", "target": "逆态度"},
	{"source": "逆战", "target": "何必在一起"},
	{"source": "逆战", "target": "剑心"},
	{"source": "逆态度", "target": "仰望星空"},
	{"source": "逆态度", "target": "他不懂"},
	{"source": "逆态度", "target": "天下"},
	{"source": "逆态度", "target": "如果爱"},
	{"source": "逆态度", "target": "逆战"},
	{"source": "逆态度", "target": "逆态度"},
	{"source": "逆态度", "target": "何必在一起"},
	{"source": "逆态度", "target": "剑心"},
	{"source": "何必在一起", "target": "仰望星空"},
	{"source": "何必在一起", "target": "他不懂"},
	{"source": "何必在一起", "target": "天下"},
	{"source": "何必在一起", "target": "如果爱"},
	{"source": "何必在一起", "target": "逆战"},
	{"source": "何必在一起", "target": "逆态度"},
	{"source": "何必在一起", "target": "何必在一起"},
	{"source": "何必在一起", "target": "剑心"},
	{"source": "剑心", "target": "仰望星空"},
	{"source": "剑心", "target": "他不懂"},
	{"source": "剑心", "target": "天下"},
	{"source": "剑心", "target": "如果爱"},
	{"source": "剑心", "target": "逆战"},
	{"source": "剑心", "target": "逆态度"},
	{"source": "剑心", "target": "何必在一起"},
	{"source": "剑心", "target": "剑心"},
	{"source": "仰望星空", "target": "稻香"},
	{"source": "稻香", "target": "稻香"},
	{"source": "稻香", "target": "告白气球"},
	{"source": "稻香", "target": "夜曲"},
	{"source": "稻香", "target": "红尘客栈"},
	{"source": "稻香", "target": "开不了口"},
	{"source": "稻香", "target": "菊花台"},
	{"source": "稻香", "target": "牛仔很忙"},
	{"source": "稻香", "target": "烟花易冷"},
	{"source": "稻香", "target": "听妈妈的话"},
	{"source": "稻香", "target": "七里香"},
	{"source": "稻香", "target": "晴天"},
	{"source": "告白气球", "target": "稻香"},
	{"source": "告白气球", "target": "告白气球"},
	{"source": "告白气球", "target": "夜曲"},
	{"source": "告白气球", "target": "红尘客栈"},
	{"source": "告白气球", "target": "开不了口"},
	{"source": "告白气球", "target": "菊花台"},
	{"source": "告白气球", "target": "牛仔很忙"},
	{"source": "告白气球", "target": "烟花易冷"},
	{"source": "告白气球", "target": "听妈妈的话"},
	{"source": "告白气球", "target": "七里香"},
	{"source": "告白气球", "target": "晴天"},
	{"source": "夜曲", "target": "稻香"},
	{"source": "夜曲", "target": "告白气球"},
	{"source": "夜曲", "target": "夜曲"},
	{"source": "夜曲", "target": "红尘客栈"},
	{"source": "夜曲", "target": "开不了口"},
	{"source": "夜曲", "target": "菊花台"},
	{"source": "夜曲", "target": "牛仔很忙"},
	{"source": "夜曲", "target": "烟花易冷"},
	{"source": "夜曲", "target": "听妈妈的话"},
	{"source": "夜曲", "target": "七里香"},
	{"source": "夜曲", "target": "晴天"},
	{"source": "红尘客栈", "target": "稻香"},
	{"source": "红尘客栈", "target": "告白气球"},
	{"source": "红尘客栈", "target": "夜曲"},
	{"source": "红尘客栈", "target": "红尘客栈"},
	{"source": "红尘客栈", "target": "开不了口"},
	{"source": "红尘客栈", "target": "菊花台"},
	{"source": "红尘客栈", "target": "牛仔很忙"},
	{"source": "红尘客栈", "target": "烟花易冷"},
	{"source": "红尘客栈", "target": "听妈妈的话"},
	{"source": "红尘客栈", "target": "七里香"},
	{"source": "红尘客栈", "target": "晴天"},
	{"source": "开不了口", "target": "稻香"},
	{"source": "开不了口", "target": "告白气球"},
	{"source": "开不了口", "target": "夜曲"},
	{"source": "开不了口", "target": "红尘客栈"},
	{"source": "开不了口", "target": "开不了口"},
	{"source": "开不了口", "target": "菊花台"},
	{"source": "开不了口", "target": "牛仔很忙"},
	{"source": "开不了口", "target": "烟花易冷"},
	{"source": "开不了口", "target": "听妈妈的话"},
	{"source": "开不了口", "target": "七里香"},
	{"source": "开不了口", "target": "晴天"},
	{"source": "菊花台", "target": "稻香"},
	{"source": "菊花台", "target": "告白气球"},
	{"source": "菊花台", "target": "夜曲"},
	{"source": "菊花台", "target": "红尘客栈"},
	{"source": "菊花台", "target": "开不了口"},
	{"source": "菊花台", "target": "菊花台"},
	{"source": "菊花台", "target": "牛仔很忙"},
	{"source": "菊花台", "target": "烟花易冷"},
	{"source": "菊花台", "target": "听妈妈的话"},
	{"source": "菊花台", "target": "七里香"},
	{"source": "菊花台", "target": "晴天"},
	{"source": "牛仔很忙", "target": "稻香"},
	{"source": "牛仔很忙", "target": "告白气球"},
	{"source": "牛仔很忙", "target": "夜曲"},
	{"source": "牛仔很忙", "target": "红尘客栈"},
	{"source": "牛仔很忙", "target": "开不了口"},
	{"source": "牛仔很忙", "target": "菊花台"},
	{"source": "牛仔很忙", "target": "牛仔很忙"},
	{"source": "牛仔很忙", "target": "烟花易冷"},
	{"source": "牛仔很忙", "target": "听妈妈的话"},
	{"source": "牛仔很忙", "target": "七里香"},
	{"source": "牛仔很忙", "target": "晴天"},
	{"source": "烟花易冷", "target": "稻香"},
	{"source": "烟花易冷", "target": "告白气球"},
	{"source": "烟花易冷", "target": "夜曲"},
	{"source": "烟花易冷", "target": "红尘客栈"},
	{"source": "烟花易冷", "target": "开不了口"},
	{"source": "烟花易冷", "target": "菊花台"},
	{"source": "烟花易冷", "target": "牛仔很忙"},
	{"source": "烟花易冷", "target": "烟花易冷"},
	{"source": "烟花易冷", "target": "听妈妈的话"},
	{"source": "烟花易冷", "target": "七里香"},
	{"source": "烟花易冷", "target": "晴天"},
	{"source": "听妈妈的话", "target": "稻香"},
	{"source": "听妈妈的话", "target": "告白气球"},
	{"source": "听妈妈的话", "target": "夜曲"},
	{"source": "听妈妈的话", "target": "红尘客栈"},
	{"source": "听妈妈的话", "target": "开不了口"},
	{"source": "听妈妈的话", "target": "菊花台"},
	{"source": "听妈妈的话", "target": "牛仔很忙"},
	{"source": "听妈妈的话", "target": "烟花易冷"},
	{"source": "听妈妈的话", "target": "听妈妈的话"},
	{"source": "听妈妈的话", "target": "七里香"},
	{"source": "听妈妈的话", "target": "晴天"},
	{"source": "七里香", "target": "稻香"},
	{"source": "七里香", "target": "告白气球"},
	{"source": "七里香", "target": "夜曲"},
	{"source": "七里香", "target": "红尘客栈"},
	{"source": "七里香", "target": "开不了口"},
	{"source": "七里香", "target": "菊花台"},
	{"source": "七里香", "target": "牛仔很忙"},
	{"source": "七里香", "target": "烟花易冷"},
	{"source": "七里香", "target": "听妈妈的话"},
	{"source": "七里香", "target": "七里香"},
	{"source": "七里香", "target": "晴天"},
	{"source": "晴天", "target": "稻香"},
	{"source": "晴天", "target": "告白气球"},
	{"source": "晴天", "target": "夜曲"},
	{"source": "晴天", "target": "红尘客栈"},
	{"source": "晴天", "target": "开不了口"},
	{"source": "晴天", "target": "菊花台"},
	{"source": "晴天", "target": "牛仔很忙"},
	{"source": "晴天", "target": "烟花易冷"},
	{"source": "晴天", "target": "听妈妈的话"},
	{"source": "晴天", "target": "七里香"},
  {"source": "晴天", "target": "晴天"},
  {"source": "江南", "target": "七里香"},
],


    };
  },
};
</script>

<style lang="scss" scoped>
@import '../assets/css/music-continent.scss';
</style>